version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com      
  build:
    commands:
      - docker build -t rails-ecr api/
      - docker tag rails-ecr:latest 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com/rails-ecr:latest;
      - docker push 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com/rails-ecr:latest
      
      - docker build -t nuxt-ecr front/
      - docker tag nuxt-ecr:latest 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com/nuxt-ecr:latest;
      - docker push 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com/nuxt-ecr:latest
  post_build:
    commands:
      - printf '[{"name":"api-container","imageUri":"%s"}]' rails-ecr > api_imagedefinitions.json
      - printf '[{"name":"front-container","imageUri":"%s"}]' nuxt-ecr > front_imagedefinitions.json
artifacts:
  files:
    - api_imagedefinitions.json
    - front_imagedefinitions.json