version: 0.2

env:
  parameter-store:
    DOCKERHUB_USER: dockerhub-user
    DOCKERHUB_PASS: dockerhub-pass

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 667123667048.dkr.ecr.ap-northeast-1.amazonaws.com;
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
  build:
    commands:
      - docker build -t rails-ecr api/
      - docker push rails-ecr
      - docker build -t nuxt-ecr front/
      - docker push nuxt-ecr
  post_build:
    commands:
      - printf '[{"name":"api-container","imageUri":"%s"}]' rails-ecr > api_imagedefinitions.json
      - printf '[{"name":"front-container","imageUri":"%s"}]' nuxt-ecr > front_imagedefinitions.json
artifacts:
  files:
    - api_imagedefinitions.json
    - front_imagedefinitions.json