version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR:               $WORKDIR
        AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        DB_HOST:               $DB_HOST
        DB_NAME:               $DB_NAME
        DB_USERNAME:           $DB_USERNAME
        POSTGRES_PASSWORD:     $POSTGRES_PASSWORD
        S3_REGION:             $S3_REGION
        S3_BUCKET:             $S3_BUCKET
        RAILS_MASTER_KEY:      $RAILS_MASTER_KEY

    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./api:/$WORKDIR
      - api-bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "3000:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  db-data:
  api-bundle:
  front-node_modules: